name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npx turbo run build --filter @senscience/curvenote-editor

      - name: Typecheck
        run: npx tsc --noEmit
        working-directory: packages/editor
